# yaml-language-server: $schema=https://github.com/DavidAnson/markdownlint-cli2/raw/refs/heads/main/schema/markdownlint-cli2-config-schema.json

config:
  default: true
  fix: true
  line-length:
    line_length: 100
    tables: false
    code_blocks: false
  no-inline-html:
    allowed_elements:
      - br
  no-duplicate-heading: false
  no-trailing-spaces:
    br_spaces: 0
