name: recyclarr

networks:
  recyclarr:
    name: recyclarr_dev
    external: true

services:
  app:
    image: ghcr.io/recyclarr/recyclarr:edge
    user: $DOCKER_UID:$DOCKER_GID
    container_name: recyclarr
    read_only: true
    tmpfs: /tmp
    build:
      context: .
      # platforms:
        # - linux/arm/v7
        # - linux/arm64
        # - linux/amd64
    networks: [recyclarr]
    volumes:
      - ./docker/config:/config
    environment:
      CRON_SCHEDULE: "* * * * *"
      TZ: America/Chicago
