name: Bug Report
description: Create a report to help us improve
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    validations: { required: true }
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
  - type: textarea
    validations: { required: true }
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
  - type: textarea
    validations: { required: true }
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
  - type: textarea
    validations: { required: true }
    attributes:
      label: Environment & Versions
      render: bash
      description: |
        Please provide information about your environment below. If certain information is not
        relevant to your issue, you may omit it. Feel free to add more information than what is
        shown here as well, especially if it's directly related to the issue and will help debug the
        problem and/or find a solution.

        Examples:

        - Operating System: `Windows 10 / Ubuntu 22.04 / Docker`
        - Recyclarr Version: `v3.0.0`
        - Sonarr Version: `3.0.9.1549`
        - Radarr Version: `4.3.0.6671`
      value: |
        - Operating System:
        - Recyclarr Version:
        - Sonarr Version:
        - Radarr Version:
  - type: textarea
    validations: { required: true }
    attributes:
      label: Recyclarr Log File(s)
      placeholder: Drag & Drop your Recyclarr log file(s) here.
      description: >
        Attach one or more [log files](https://recyclarr.dev/wiki/troubleshooting#obtaining-debug-logs)
        that are relevant to the issue. Due to the size of these files, I do not recommend pasting
        it here.
  - type: textarea
    validations: { required: true }
    attributes:
      label: Configuration YAML
      render: YAML
      description: >
        Provide your [redacted](https://recyclarr.dev/wiki/troubleshooting/#redact-config)
        configuration YAML here (e.g. `recyclarr.yml`).
  - type: textarea
    attributes:
      label: Sonarr / Radarr Logs
      description: >
        If the issue is related to an issue on the Sonarr or Radarr side, provide the logs here as
        an attachment or [fenced code
        block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).
