networks:
  recyclarr:
    name: recyclarr_dev
    external: true

services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:edge
    user: $DOCKER_UID:$DOCKER_GID
    build:
      context: .
      args:
        - TARGETPLATFORM=linux/amd64
    init: true
    networks: [recyclarr]
    volumes:
      - ./config:/config
    environment:
      CRON_SCHEDULE: "* * * * *"
      TZ: America/Chicago
