name: Setup mise with PATH
description: Setup mise and configure PATH for GitHub Actions
runs:
  using: composite
  steps:
    - name: Setup mise
      uses: jdx/mise-action@v2
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_NOLOGO: 1
      with:
        experimental: true
        log_level: trace
        reshim: true
