# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Quick Build & Test

on:
  pull_request:
  push:
    branches-ignore: [master]

permissions: read-all

jobs:
  #############################################
  pre-check:
    name: Check for Duplicate Runs
    uses: ./.github/workflows/reusable-precheck.yml

  #############################################
  build-validation:
    name: Build Validation
    needs: pre-check
    if: needs.pre-check.outputs.should_run == 'true'
    secrets: inherit
    uses: ./.github/workflows/reusable-build.yml
    with:
      platform: ubuntu-latest
      runtime: linux-x64

  #############################################
  docker-validation:
    name: Docker Validation
    needs: [build-validation]
    permissions:
      packages: write
    uses: ./.github/workflows/reusable-docker.yml
    secrets: inherit

  #############################################
  # The main purpose of this job is to group all the other jobs together into one single job status
  # that can be set as a requirement to merge pull requests. This is easier than enumerating all
  # jobs in a workflow to ensure they all pass.
  post-check:
    if: always()
    name: Report Quick Build Status
    needs:
      - build-validation
      - docker-validation
    runs-on: ubuntu-latest
    steps:
      - name: Check if all jobs succeeded
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
