# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Docker Retention

on:
  workflow_dispatch: # TEMP
  schedule:
    - cron: '0 0 * * *'

jobs:
  retention:
    name: Enforce Retention Policy
    runs-on: ubuntu-latest
    steps:
      - name: Delete old pre-release images
        uses: snok/container-retention-policy@v2
        with:
          image-names: recyclarr
          filter-tags: '*-dev.*'
          cut-off: One week ago CST
          keep-at-least: 1
          account-type: org
          org-name: recyclarr
          token: ${{ secrets.GITHUB_TOKEN }}
          token-type: github-token
          dry-run: true # TEMP
