name: Release Notification

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string
        description: The release tag to generate a notification for

env:
  TAG: ${{ github.event.release.tag_name || github.event.inputs.tag_name }}

jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install discord-webhook
      - run: |
          python ci/notify/discord_notify.py \
            '${{ github.event.release.tag_name }}' \
            '${{ secrets.DISCORD_WEBHOOK }}' \
            '${{ github.event.release.body }}'
