# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Pre-Check for Duplicate Runs

on:
  workflow_call:
    outputs:
      should_run:
        description: Whether the calling workflow should run (false if push event has a PR)
        value: ${{ jobs.precheck.outputs.should_run }}

permissions: read-all

jobs:
  precheck:
    name: Check for Duplicate Runs
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Check if push event has corresponding PR
        id: check
        run: |
          # Always run for non-push events (prioritize PR builds, workflow_dispatch, etc.)
          if [[ "${{ github.event_name }}" != "push" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
            echo "Event type: ${{ github.event_name }} - allowing run"
            exit 0
          fi

          # For push events, check if there's an open PR for this SHA
          echo "Checking for PRs associated with commit ${{ github.sha }}"
          PR_COUNT=$(gh api repos/${{ github.repository }}/commits/${{ github.sha }}/pulls \
            --jq 'length' 2>/dev/null || echo "0")

          if [[ "$PR_COUNT" -gt 0 ]]; then
            echo "should_run=false" >> $GITHUB_OUTPUT
            echo "Found $PR_COUNT PR(s) for this commit - skipping push event run"
          else
            echo "should_run=true" >> $GITHUB_OUTPUT
            echo "No PRs found for this commit - allowing push event run"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
