# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Sonarcloud

on:
  # Do not run on pull-request because the required tokens
  # cannot be read from there.
  push:
    # Explicitly specifying this results in tags being ignored, which is the goal.
    branches: ["**"]
    paths:
      - .github/workflows/sonarcloud.yml
      - sonar-project.properties
      - '**.props'
      - 'src/**'
      - 'tests/**'
      - 'ci/**'

  pull_request:
    paths:
      - .github/workflows/sonarcloud.yml
      - sonar-project.properties
      - '**.props'
      - 'src/**'
      - 'tests/**'
      - 'ci/**'

permissions: read-all

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Get Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone for GitVersion and Sonar analysis

      - name: Setup mise
        uses: ./.github/actions/setup-mise

      - name: Perform Scan
        run: pwsh ci/RunSonarScan.ps1 -SonarToken "${{ secrets.SONAR_TOKEN }}"
